WORDS = {
    "animals": {
        "easy": ["CAT", "DOG", "BIRD", "FISH", "FROG", "COW", "PIG", "ANT", "BAT", "LION", "BEAR", "DEER", "WOLF", "DUCK", "MOUSE"],
        "medium": ["ELEPHANT", "GIRAFFE", "PENGUIN", "KANGAROO", "OCTOPUS", "DOLPHIN", "LEOPARD", "CAMEL", "PEACOCK", "KOALA", "PANDA", "ZEBRA", "CHEETAH", "GORILLA", "RACCOON"],
        "hard": ["PLATYPUS", "CHIMPANZEE", "HIPPOPOTAMUS", "RHINOCEROS", "CHAMELEON", "ARMADILLO", "JAGUAR", "NARWHAL", "WOLVERINE", "WALLABY", "AXOLOTL", "LEMUR", "PANGOLIN", "QUOKKA", "TAPIR"]
    },
    "countries": {
        "easy": ["USA", "CANADA", "FRANCE", "SPAIN", "ITALY", "INDIA", "CHINA", "JAPAN", "RUSSIA", "MEXICO", "BRAZIL", "ENGLAND", "GERMANY", "AUSTRALIA", "KOREA"],
        "medium": ["AUSTRALIA", "GERMANY", "BRAZIL", "JAPAN", "EGYPT", "ARGENTINA", "TURKEY", "SOUTH AFRICA", "THAILAND", "UKRAINE", "SWEDEN", "NORWAY", "PORTUGAL", "IRELAND", "GREECE"],
        "hard": ["KAZAKHSTAN", "MOZAMBIQUE", "VENEZUELA", "PHILIPPINES", "BANGLADESH", "KYRGYZSTAN", "UZBEKISTAN", "SRI LANKA", "LIECHTENSTEIN", "ANDORRA", "BHUTAN", "SURINAME", "MAURITIUS", "ESWATINI", "VANUATU"]
    },
    "foods": {
        "easy": ["PIZZA", "PASTA", "BREAD", "APPLE", "CAKE", "BURGER", "SALAD", "SOUP", "SANDWICH", "FRIES", "RICE", "EGGS", "CHEESE", "CHICKEN", "STEAK"],
        "medium": ["SUSHI", "BURGER", "LASAGNA", "PANCAKE", "OMELETTE", "RISOTTO", "TACOS", "FAJITAS", "CURRY", "PAELLA", "KEBAB", "QUESADILLA", "PESTO", "CROISSANT", "RAMEN"],
        "hard": ["RATATOUILLE", "BOUILLABAISSE", "GNOCCHI", "POUTINE", "GUACAMOLE", "BIBIMBAP", "MOLE", "COQ AU VIN", "TZATZIKI", "BOBOTIE", "BORSCHT", "CEVICHE", "SPANAKOPITA", "HAGGIS", "KIMCHI"]
    },
    "fruits": {
        "easy": ["APPLE", "BANANA", "ORANGE", "GRAPE", "PEAR", "KIWI", "MANGO", "LEMON", "PEACH", "PLUM", "CHERRY", "MELON", "LIME", "BERRY", "FIG"],
        "medium": ["PINEAPPLE", "PAPAYA", "POMEGRANATE", "LITCHI", "COCONUT", "GUAVA", "AVOCADO", "DRAGONFRUIT", "PASSIONFRUIT", "DURIAN", "APRICOT", "NECTARINE", "BLACKBERRY", "CANTALOUPE", "TANGERINE"],
        "hard": ["PERSIMMON", "RAMBUTAN", "JACKFRUIT", "KUMQUAT", "SALAK", "SAPOTE", "QUINCE", "CARAMBOLA", "CUSTARD APPLE", "FEIJOA", "SOURSOP", "LOQUAT", "MANGOSTEEN", "CHERIMOYA", "UGLI FRUIT"]
    },
    "vegetables": {
        "easy": ["CARROT", "POTATO", "TOMATO", "ONION", "PEAS", "CORN", "CUCUMBER", "SPINACH", "LETTUCE", "PEPPER", "CELERY", "GARLIC", "BROCCOLI", "BEANS", "RADISH"],
        "medium": ["BROCCOLI", "CAULIFLOWER", "ASPARAGUS", "EGGPLANT", "ZUCCHINI", "ARTICHOKE", "BEETROOT", "BRUSSELS SPROUTS", "CABBAGE", "KALE", "PARSNIP", "TURNIP", "LEEK", "SQUASH", "SHALLOT"],
        "hard": ["KOHLRABI", "RADICCHIO", "FENNEL", "JICAMA", "OKRA", "CELERIAC", "SORREL", "SCALLION", "CHAYOTE", "WATERCRESS", "ENDIVE", "SALSIFY", "FIDDLEHEAD", "NOPALES", "SUNCHOKE"]
    },
    "colors": {
        "easy": ["RED", "BLUE", "GREEN", "YELLOW", "PINK", "ORANGE", "PURPLE", "BROWN", "BLACK", "WHITE", "GRAY", "GOLD", "SILVER", "BEIGE", "NAVY"],
        "medium": ["TURQUOISE", "VIOLET", "MAGENTA", "CYAN", "LIME", "CRIMSON", "INDIGO", "GOLDENROD", "SALMON", "SLATE", "MAROON", "TEAL", "OLIVE", "KHAKI", "PLUM"],
        "hard": ["CERULEAN", "VERMILION", "CHARTREUSE", "AMETHYST", "PERIWINKLE", "MAUVE", "TANGERINE", "CORNFLOWER", "SANGUINE", "TAUPE", "FUCHSIA", "CELADON", "PUCE", "OCHRE", "SEPIA"]
    },
    "sports": {
        "easy": ["SOCCER", "BASKETBALL", "BASEBALL", "TENNIS", "CRICKET", "GOLF", "HOCKEY", "RUGBY", "VOLLEYBALL", "SWIMMING", "FOOTBALL", "RUNNING", "CYCLING", "SKATING", "SKIING"],
        "medium": ["HANDBALL", "BADMINTON", "SQUASH", "WRESTLING", "BOXING", "CYCLING", "KAYAKING", "SURFING", "SKIING", "SNOWBOARDING", "ARCHERY", "FENCING", "JUDO", "ROWING", "DIVING"],
        "hard": ["PENTATHLON", "TRAMPOLINING", "EQUESTRIAN", "LUGE", "SKELETON", "BOBSLEIGH", "CURLING", "CAVING", "SPEEDWAY", "PARKOUR", "SEPAK TAKRAW", "KORFBALL", "HURLING", "KABADDI", "TCHOUKBALL"]
    }
}