WORDS = {
    "animals": {
        "easy": ["CAT", "DOG", "BIRD", "FISH", "FROG", "COW", "PIG", "ANT", "BAT", "LION", "BEAR", "DEER", "WOLF", "DUCK", "MOUSE", "HORSE", "SHEEP", "GOAT"],
        "medium": ["ELEPHANT", "GIRAFFE", "PENGUIN", "KANGAROO", "OCTOPUS", "DOLPHIN", "LEOPARD", "CAMEL", "PEACOCK", "KOALA", "PANDA", "ZEBRA", "CHEETAH", "GORILLA", "RACCOON", "OTTER", "SEAL", "ALPACA"],
        "hard": ["PLATYPUS", "CHIMPANZEE", "HIPPOPOTAMUS", "RHINOCEROS", "CHAMELEON", "ARMADILLO", "JAGUAR", "NARWHAL", "WOLVERINE", "WALLABY", "AXOLOTL", "LEMUR", "PANGOLIN", "QUOKKA", "TAPIR", "ORYX", "AARDVARK", "ECHIDNA"]
    },
    "countries": {
        "easy": ["USA", "CANADA", "FRANCE", "SPAIN", "ITALY", "INDIA", "CHINA", "JAPAN", "RUSSIA", "MEXICO", "BRAZIL", "ENGLAND", "GERMANY", "AUSTRALIA", "KOREA", "SWITZERLAND", "NETHERLANDS", "AUSTRIA"],
        "medium": ["AUSTRALIA", "GERMANY", "BRAZIL", "JAPAN", "EGYPT", "ARGENTINA", "TURKEY", "SOUTH AFRICA", "THAILAND", "UKRAINE", "SWEDEN", "NORWAY", "PORTUGAL", "IRELAND", "GREECE", "PERU", "CHILE", "MOROCCO"],
        "hard": ["KAZAKHSTAN", "MOZAMBIQUE", "VENEZUELA", "PHILIPPINES", "BANGLADESH", "KYRGYZSTAN", "UZBEKISTAN", "SRI LANKA", "LIECHTENSTEIN", "ANDORRA", "BHUTAN", "SURINAME", "MAURITIUS", "ESWATINI", "VANUATU", "LESOTHO", "MYANMAR", "TURKMENISTAN"]
    },
    "foods": {
        "easy": ["PIZZA", "PASTA", "BREAD", "CAKE", "BURGER", "SALAD", "SOUP", "SANDWICH", "FRIES", "RICE", "EGGS", "CHEESE", "CHICKEN", "STEAK", "GRAPES", "PEANUTS", "YOGURT"],
        "medium": ["SUSHI", "BURGER", "LASAGNA", "PANCAKE", "OMELETTE", "RISOTTO", "TACOS", "FAJITAS", "CURRY", "PAELLA", "KEBAB", "QUESADILLA", "PESTO", "CROISSANT", "RAMEN", "DIM SUM", "MEATLOAF", "FONDUE"],
        "hard": ["RATATOUILLE", "BOUILLABAISSE", "GNOCCHI", "POUTINE", "GUACAMOLE", "BIBIMBAP", "MOLE", "COQ AU VIN", "TZATZIKI", "BOBOTIE", "BORSCHT", "CEVICHE", "SPANAKOPITA", "HAGGIS", "KIMCHI", "SOUFFLE", "MARMITE", "TAPENADE"]
    },
    "fruits": {
        "easy": ["APPLE", "BANANA", "ORANGE", "GRAPE", "PEAR", "KIWI", "MANGO", "LEMON", "PEACH", "PLUM", "CHERRY", "MELON", "LIME", "BERRY", "FIG", "STRAWBERRY", "BLUEBERRY", "PINEAPPLE"],
        "medium": ["PINEAPPLE", "PAPAYA", "POMEGRANATE", "LITCHI", "COCONUT", "GUAVA", "AVOCADO", "DRAGONFRUIT", "PASSIONFRUIT", "DURIAN", "APRICOT", "NECTARINE", "BLACKBERRY", "CANTALOUPE", "TANGERINE", "RAMBUTAN", "CLEMENTINE", "GUANABANA"],
        "hard": ["PERSIMMON", "RAMBUTAN", "JACKFRUIT", "KUMQUAT", "SALAK", "SAPOTE", "QUINCE", "CARAMBOLA", "CUSTARD APPLE", "FEIJOA", "SOURSOP", "LOQUAT", "MANGOSTEEN", "CHERIMOYA", "UGLI FRUIT", "PRICKLY PEAR", "MEDLAR", "CAPE GOOSEBERRY"]
    },
    "vegetables": {
        "easy": ["CARROT", "POTATO", "TOMATO", "ONION", "PEAS", "CORN", "CUCUMBER", "SPINACH", "LETTUCE", "PEPPER", "CELERY", "GARLIC", "BROCCOLI", "BEANS", "RADISH", "PUMPKIN", "ZUCCHINI", "SWEET POTATO"],
        "medium": ["BROCCOLI", "CAULIFLOWER", "ASPARAGUS", "EGGPLANT", "ZUCCHINI", "ARTICHOKE", "BEETROOT", "BRUSSELS SPROUTS", "CABBAGE", "KALE", "PARSNIP", "TURNIP", "LEEK", "SQUASH", "SHALLOT", "SWISS CHARD", "COLLARD GREENS", "WATER CHESTNUT"],
        "hard": ["KOHLRABI", "RADICCHIO", "FENNEL", "JICAMA", "OKRA", "CELERIAC", "SORREL", "SCALLION", "CHAYOTE", "WATERCRESS", "ENDIVE", "SALSIFY", "FIDDLEHEAD", "NOPALES", "SUNCHOKE", "MIZUNA", "RUTABAGA", "KOMATSUNA"]
    },
    "colors": {
        "easy": ["RED", "BLUE", "GREEN", "YELLOW", "PINK", "ORANGE", "PURPLE", "BROWN", "BLACK", "WHITE", "GRAY", "GOLD", "SILVER", "BEIGE", "NAVY", "AQUA", "MINT", "PEACH"],
        "medium": ["TURQUOISE", "VIOLET", "MAGENTA", "CYAN", "LIME", "CRIMSON", "INDIGO", "GOLDENROD", "SALMON", "SLATE", "MAROON", "TEAL", "OLIVE", "KHAKI", "PLUM", "PERIWINKLE", "CINNAMON", "MUSTARD"],
        "hard": ["CERULEAN", "VERMILION", "CHARTREUSE", "AMETHYST", "PERIWINKLE", "MAUVE", "TANGERINE", "CORNFLOWER", "SANGUINE", "TAUPE", "FUCHSIA", "CELADON", "PUCE", "OCHRE", "SEPIA", "HELIOTROPE", "COQUELICOT", "VERDIGRIS"]
    },
    "sports": {
        "easy": ["SOCCER", "BASKETBALL", "BASEBALL", "TENNIS", "CRICKET", "GOLF", "HOCKEY", "RUGBY", "VOLLEYBALL", "SWIMMING", "FOOTBALL", "RUNNING", "CYCLING", "SKATING", "SKIING", "BADMINTON", "DARTS", "TABLE TENNIS"],
        "medium": ["HANDBALL", "BADMINTON", "SQUASH", "WRESTLING", "BOXING", "CYCLING", "KAYAKING", "SURFING", "SKIING", "SNOWBOARDING", "ARCHERY", "FENCING", "JUDO", "ROWING", "DIVING", "TAE KWON DO", "CROQUET", "LACROSSE"],
        "hard": ["PENTATHLON", "TRAMPOLINING", "EQUESTRIAN", "LUGE", "SKELETON", "BOBSLEIGH", "CURLING", "CAVING", "SPEEDWAY", "PARKOUR", "SEPAK TAKRAW", "KORFBALL", "HURLING", "KABADDI", "TCHOUKBALL", "CANOEING", "DODEBALL", "CRICKET"]
    },
    "occupations": {
        "easy": ["TEACHER", "DOCTOR", "ENGINEER", "NURSE", "FIREFIGHTER", "POLICE OFFICER", "CHEF", "FARMER", "VETERINARIAN", "ACTOR", "MUSICIAN", "WRITER", "SCIENTIST", "PHOTOGRAPHER", "CARPENTER", "DRIVER", "CASHIER", "BAKER"],
        "medium": ["SCIENTIST", "PHOTOGRAPHER", "CARPENTER", "LAWYER", "MECHANIC", "PLUMBER", "ELECTRICIAN", "DENTIST", "PHARMACIST", "ARCHITECT", "ACCOUNTANT", "CHEMIST", "BOTANIST", "LIBRARIAN", "SURVEYOR", "NUTRITIONIST"],
        "hard": ["ARCHEOLOGIST", "MICROBIOLOGIST", "AEROSPACE ENGINEER", "NEUROLOGIST", "BIOCHEMIST", "METEOROLOGIST", "EPIDEMIOLOGIST", "RADIOLOGIST", "ENDOCRINOLOGIST", "GENETICIST", "COSMOLOGIST", "ENTOMOLOGIST", "TOXICOLOGIST", "PALEONTOLOGIST", "GEOLOGIST", "CYBERSECURITY ANALYST", "ACTUARY", "BIOINFORMATICIAN"]
    },
    "actions": {
        "easy": ["RUN", "JUMP", "EAT", "DRINK", "SLEEP", "READ", "WRITE", "TALK", "LISTEN", "WALK", "SIT", "STAND", "PLAY", "WORK", "DRIVE", "LAUGH", "CRY", "THINK"],
        "medium": ["DISCUSS", "EXPLAIN", "NEGOTIATE", "OBSERVE", "DESCRIBE", "ANALYZE", "COMPARE", "MEASURE", "RESEARCH", "INVESTIGATE", "IMAGINE", "CREATE", "PREDICT", "SOLVE", "SYNTHESIZE", "ORGANIZE", "COLLABORATE", "PRESENT"],
        "hard": ["HYPOTHESIZE", "IMPLEMENT", "CONCEPTUALIZE", "INTERPRET", "DEDUCT", "EVALUATE", "CRITIQUE", "FORMULATE", "THEORIZE", "SYSTEMATIZE", "INNOVATE", "RECONCILE", "RESTRUCTURE", "QUANTIFY", "OPERATIONALIZE", "OPTIMIZE", "STRATEGIZE", "EXTRAPOLATE"]
    },
    "adjectives": {
        "easy": ["BIG", "SMALL", "HAPPY", "SAD", "FAST", "SLOW", "HOT", "COLD", "NEW", "OLD", "GOOD", "BAD", "RED", "BLUE", "GREEN", "BRIGHT", "DARK", "LOVELY"],
        "medium": ["FURIOUS", "EXCITED", "MYSTERIOUS", "CURIOUS", "NERVOUS", "ANXIOUS", "JOYFUL", "SLEEPY", "GRUMPY", "BREEZY", "CLOUDY", "FOGGY", "RAINY", "SUNNY", "WINDY", "THRILLED", "CONFIDENT", "THOUGHTFUL"],
        "hard": ["UNFATHOMABLE", "INCONCEIVABLE", "INEXPLICABLE", "MELANCHOLIC", "EXUBERANT", "FLABBERGASTED", "DISCOMBOBULATED", "INTERMINABLE", "INSURMOUNTABLE", "INDEFATIGABLE", "OMNIPOTENT", "OMNISCIENT", "MAGNANIMOUS", "INEFFABLE", "UNQUANTIFIABLE", "OMNIPRESENT", "PRODIGIOUS", "IMPENETRABLE"]
    }
}
